### ISSUE TITLE
Message registry with fetcher can't resolve dependencies on well known types

### ISSUE THREAD

**Issue by geoah** [jhump/protoreflect#165]
I'm trying to wrap my head around how to get the message registry to fall back to well known types when using the fetcher. 

When using a custom fetcher it tries to fetch the types that it doesn't know about, and then the parser tries to find their dependencies which in our case is `google/protobuf/any.proto`. (testcase A).

Normally when the parser asks the accessor for a type that it doesn't know about, it checks the well known types after that. (testcase B)

But this doesn't to be the case when I do this through the fetcher.

In both my test cases the accessor returns an error when it doesn't find something (tried with returning `nil, nil` as in some places in the lib with worst results hehe).

ps. Your fetcher tests seem to be able to get the duration wkt so I assume it's not a bug and that I'm just missing something or that I'm just doing wrong.

---

@jhump thank you again for your help and sorry for the weird questions and long tests. hopefully I'll get a better grasp of the lib and stop spamming :D

### Testcase A

```golang
package dynamic

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"strings"
	"testing"

	"github.com/davecgh/go-spew/spew"
	"github.com/golang/protobuf/jsonpb"
	"github.com/golang/protobuf/proto"
	"github.com/jhump/protoreflect/desc/protoparse"
	"github.com/jhump/protoreflect/dynamic"
	"github.com/jhump/protoreflect/dynamic/msgregistry"
	"github.com/stretchr/testify/assert"
)

var ErrNotFound = errors.New("not found")

var files = map[string]string{
	"https://test/core.wrapper.proto": `
		syntax = "proto3";
		package core;
		import "google/protobuf/any.proto";
		message wrapper {
			string abc = 1;
			int32 def = 2;
			repeated google.protobuf.Any extras = 3;
		}`,
	"https://test/core.one.proto": `
		syntax = "proto3";
		package core;
		message one {
			string abc = 1;
			int32 def = 2;
		}`,
	"https://test/core.two.proto": `
		syntax = "proto3";
		package core;
		message two {
			string ghi = 1;
			int32 jkl = 2;
		}`,
}

func fqnFromURL(url string) string {
	// TODO replace with regex or find something in protoreflect that does this?
	ps := strings.Split(url, "/")
	fqn := ps[0]
	if i := len(ps); i > 1 {
		fqn = ps[i-1]
	}
	if strings.HasSuffix(fqn, ".proto") {
		fqn = fqn[:len(fqn)-6]
	}
	return fqn
}

func TestMessageRegistryWithFetcherAndWellKnown(t *testing.T) {
	registry := (&msgregistry.MessageRegistry{}).
		WithMessageFactory(dynamic.NewMessageFactoryWithDefaults())

	reader := func(name string) (io.ReadCloser, error) {
		fmt.Println("READ:", name)
		src, ok := files[name]
		if !ok {
			fmt.Println("____ not found")
			return nil, ErrNotFound
		}
		return ioutil.NopCloser(bytes.NewReader([]byte(src))), nil
	}

	parser := &protoparse.Parser{
		Accessor: reader,
	}

	fetcher := func(url string, enum bool) (proto.Message, error) {
		fmt.Println("FETCH", url)

		fds, err := parser.ParseFiles(url)
		if err == ErrNotFound {
			return nil, nil
		}

		if err != nil {
			return nil, err
		}

		if len(fds) == 0 {
			return nil, errors.New("missing descs")
		}

		lp := fqnFromURL(url)
		fooMessage := fds[0].FindMessage(lp)
		spew.Dump(fooMessage)

		fooPType := registry.MessageAsPType(fooMessage)
		spew.Dump(fooPType)

		return fooPType, nil
	}

	registry = registry.WithFetcher(fetcher)

	md, err := registry.FindMessageTypeByUrl("https://test/core.wrapper.proto")
	assert.NoError(t, err)
	assert.NotNil(t, md)

	wr := dynamic.NewMessageFactoryWithDefaults().NewMessage(md).(*dynamic.Message)

	js := `{"extras":[{"@type":"test/core.one","abc":"fubar","def":123},{"@type":"test/core.two","abc":"snafu","def":456}]}`

	jsu := jsonpb.Unmarshaler{
		AllowUnknownFields: true,
		AnyResolver:        registry,
	}

	err = jsu.Unmarshal(strings.NewReader(js), wr)
	assert.NoError(t, err)

	spew.Dump(wr)
}
```

##### Result A

```
=== RUN   TestMessageRegistryWithFetcherAndWellKnown
FETCH: https://test/core.wrapper.proto
READ: https://test/core.wrapper.proto
READ: google/protobuf/any.proto
____ not found
([]*desc.FileDescriptor) (len=1 cap=1) {
 (*desc.FileDescriptor)(0xc0001f2540)(name:"https://test/core.wrapper.proto" package:"core" dependency:"google/protobuf/any.proto" message_type:<name:"wrapper" field:<name:"abc" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"abc" > field:<name:"def" number:2 label:LABEL_OPTIONAL type:TYPE_INT32 json_name:"def" > field:<name:"extras" number:3 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".google.protobuf.Any" json_name:"extras" > > syntax:"proto3" )
}
____ looking for https://test/core.wrapper.proto core.wrapper
(*desc.MessageDescriptor)(0xc0001f7860)(name:"wrapper" field:<name:"abc" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"abc" > field:<name:"def" number:2 label:LABEL_OPTIONAL type:TYPE_INT32 json_name:"def" > field:<name:"extras" number:3 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".google.protobuf.Any" json_name:"extras" > )
FETCH: https://type.googleapis.com/google.protobuf.Any
READ: https://type.googleapis.com/google.protobuf.Any
____ not found
--- FAIL: TestMessageRegistryWithFetcherAndWellKnown (0.00s)
    dynamic4_test.go:118:
        	Error Trace:	dynamic4_test.go:118
        	Error:      	Received unexpected error:
        	            	Failed to locate type for https://type.googleapis.com/google.protobuf.Any
        	Test:       	TestMessageRegistryWithFetcherAndWellKnown
    dynamic4_test.go:119:
        	Error Trace:	dynamic4_test.go:119
        	Error:      	Expected value not to be nil.
        	Test:       	TestMessageRegistryWithFetcherAndWellKnown
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x11ee3d8]

goroutine 20 [running]:
testing.tRunner.func1(0xc000152b00)
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:792 +0x387
panic(0x144f520, 0x1893a00)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
nope.io/go/playground/dynamic/vendor/github.com/jhump/protoreflect/desc.(*MessageDescriptor).GetFullyQualifiedName(...)
	/Users/geoah/src/nope.io/go/playground/dynamic/vendor/github.com/jhump/protoreflect/desc/descriptor.go:538
nope.io/go/playground/dynamic/vendor/github.com/jhump/protoreflect/dynamic.(*MessageFactory).NewMessage(0xc0002128d0, 0x0, 0x14b8340, 0x0)
	/Users/geoah/src/nope.io/go/playground/dynamic/vendor/github.com/jhump/protoreflect/dynamic/message_factory.go:64 +0x38
command-line-arguments.TestMessageRegistryWithFetcherAndWellKnown(0xc000152b00)
	/Users/geoah/src/nope.io/go/playground/dynamic/dynamic4_test.go:121 +0x2fd
testing.tRunner(0xc000152b00, 0x14e5430)
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:878 +0x353
FAIL	command-line-arguments	0.019s
```

### Testcase B

```golang
package dynamic

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"testing"

	"github.com/jhump/protoreflect/desc/protoparse"
	"github.com/stretchr/testify/assert"
)

var parserFiles = map[string]string{
	"https://test/core.wrapper.proto": `
		syntax = "proto3";
		package core;
		import "google/protobuf/any.proto";
		message wrapper {
			string abc = 1;
			int32 def = 2;
			repeated google.protobuf.Any extras = 3;
		}`,
}

func TestParserWithAccessor(t *testing.T) {
	reader := func(name string) (io.ReadCloser, error) {
		fmt.Println("READ:", name)
		src, ok := parserFiles[name]
		if !ok {
			fmt.Println("____ not found")
			return nil, errors.New("not found")
		}
		return ioutil.NopCloser(bytes.NewReader([]byte(src))), nil
	}

	parser := &protoparse.Parser{
		Accessor: reader,
	}

	fds, err := parser.ParseFiles("https://test/core.wrapper.proto")
	assert.NoError(t, err)
	assert.Len(t, fds, 1)
}

```

##### Result B

```
=== RUN   TestParserWithAccessor
READ: https://test/core.wrapper.proto
READ: google/protobuf/any.proto
____ not found
--- PASS: TestParserWithAccessor (0.00s)
PASS
ok  	command-line-arguments	0.014s
```

**Comment by jhump** [comment]
@geoah, you stumped the library again: fetching a type definition was not even looking at registered/known types when trying to resolve dependencies of the fetched type.

This was a glaring omission in the functionality. if you ask the registry to resolve `google.protobuf.Timestamp` it can successfully return a descriptor. But if you then need to fetch a type that happens to depend on `google.protobuf.Timestamp` (e.g. a field of that type), it fails.

You may be the first real user of this particular package. I wrote it, hoping it would help me interact with `Any` type URLs [per the spec](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any). But I've since learned that Google [no longer plans](https://groups.google.com/d/topic/protobuf/9EbqhXEZ3OI/discussion) to actually implement type registry servers. So this stuff is still in the spec, but not implemented anywhere... except this package (as far as I know anyway).

This was pretty gnarly to fix, but it seems truly required for this package to be really usable.

**Comment by geoah** [comment]
@jhump once again thank you very much for an insanely fast response and fix.
This package is an immense help in dealing with dynamic protobufs.

Everything seems to be working as perfectly after #166 -- thank you.
